# .gitlab-ci.yml
variables:
  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"   # cache Sonar
  GIT_DEPTH: "0"                                # récupère tout l'historique

stages:
  - analysis

sonarcloud-check:
  stage: analysis
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - sonar-scanner
      -Dsonar.projectKey=tp1-cloudgoat          # <-- remplace par TON projectKey SonarCloud
      -Dsonar.organization=poly-tp1             # <-- remplace par TON organization key SonarCloud
      -Dsonar.host.url=https://sonarcloud.io
      -Dsonar.login=${SONAR_TOKEN}              # <-- variable CI/CD ajoutée dans GitLab
  only:
    - main
    - merge_requests
    - develop

